module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'body-max-line-length': [2, 'always', 100], // Retain standard rules for manual commits
  },
  ignores: [
    (commit) => commit.startsWith('chore(release):'), // Ignore release commits generated by Semantic Release
  ],
};
