# .github/workflows/auto-assign.yml
name: Auto Assign PRs

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
