# .github/workflows/auto-assign.yml
name: Auto Assign PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto-label PRs
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
