# .github/workflows/auto-assign.yml
name: Auto Assign PRs

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto assign PR
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee wmitrus --add-reviewer wmitrus
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
