name: Main Branch PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  # Enhanced checks for PRs to main (develop → main only)
  # These are the final quality gates before production
  main-pr-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22] # Only test on recommended Node version for PR checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Type check
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5

      - name: Build check
        run: pnpm build

      - name: Check bundle size
        run: pnpm size

  # Validate configuration system
  config-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Validate configuration files
        run: |
          # Run standard type checking which will validate all TypeScript files including config
          pnpm typecheck

      - name: Test environment setup script
        run: |
          node scripts/setup-env.mjs check
          node scripts/setup-env.mjs create development
          node scripts/setup-env.mjs create preview
          node scripts/setup-env.mjs create staging
          node scripts/setup-env.mjs create production

      - name: Validate environment files
        run: |
          # Check that all environment files were created
          test -f .env.development
          test -f .env.preview
          test -f .env.staging
          test -f .env.production
          echo "✅ All environment files created successfully"
