name: Vercel Preview Deployment

on:
  push:
    branches-ignore:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22, 24]
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test

  Deploy-Preview:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm and tools
        run: npm install -g pnpm depcheck madge @lhci/cli @sentry/cli

      - name: Install Dependencies
        run: pnpm install

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ozi
          SENTRY_PROJECT: nextjs-15-boilerplate

      - name: Upload Source Maps to Sentry
        run: sentry-cli sourcemaps upload .next --url-prefix '~/' --rewrite
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ozi
          SENTRY_PROJECT: nextjs-15-boilerplate
          SENTRY_ENVIRONMENT: preview
          SENTRY_RELEASE: ${{ github.sha }}

      - name: Deploy Project Artifacts to Vercel
        id: vercel_deploy
        run: |
          DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --no-clipboard)
          echo "preview_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ozi
          SENTRY_PROJECT: nextjs-15-boilerplate

      - name: Set deployment URL for Lighthouse
        id: waitForVercel
        run: |
          DEPLOY_URL=${{ steps.vercel_deploy.outputs.preview_url }}
          echo "url=$DEPLOY_URL" >> $GITHUB_OUTPUT
          echo "Using deployment URL for Lighthouse: $DEPLOY_URL"

      - name: Run Lighthouse Audit with bypass
        run: |
          echo "Running Lighthouse audit on URL: ${{ steps.waitForVercel.outputs.url }}"

          # Add a longer timeout for Lighthouse and include bypass headers
          lhci autorun --collect.url=${{ steps.waitForVercel.outputs.url }} --collect.settings.maxWaitForLoad=120000 --collect.settings.extraHeaders='{"x-vercel-protection-bypass": "'"${VERCEL_AUTOMATION_BYPASS_SECRET}"'", "x-vercel-set-bypass-cookie": "samesitenone"}'
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
