name: Deploy to Linux Server
env:
  MYDEVIL_PRIVATE_KEY: ${{ secrets.MYDEVIL_PRIVATE_KEY }}
  MYDEVIL_USER: ${{ secrets.MYDEVIL_USER }}
  MYDEVIL_HOST: ${{ secrets.MYDEVIL_HOST }}
  MYDEVIL_REPO_PATH: ${{ secrets.MYDEVIL_REPO_PATH }}
  MYDEVIL_DOMAIN: ${{ secrets.MYDEVIL_DOMAIN }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MYDEVIL_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.MYDEVIL_USER }}@${{ secrets.MYDEVIL_HOST }} << 'EOF'
          cd ${{ secrets.MYDEVIL_REPO_PATH }}
          pwd
          git pull origin main
          pnpm install
          pnpm build
          devil www restart 
          EOF
